{% set version = "2.3.0" %}

package:
  name: nlp_primitives
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nlp-primitives/nlp_primitives-{{ version }}.tar.gz
  sha256: 74b333ac449d9dba5ccb2caf8d53bd93f41b74a208ac113d59863d85f9d73057

build:
  number: 0

outputs:
  - name: nlp-primitives
    build:
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - pip
        - python >=3.7.*
      run:
        - python >=3.7.*
        - numpy >=1.17.5
        - pandas >=1.3.0
        - featuretools >=1.5.0
        - nltk >=3.4.5
        - scikit-learn >=0.20.0
    test:
      commands:
        - pytest --pyargs nlp_primitives
      imports:
        - nlp_primitives
      requires:
        - pytest >=4.4.1
        - tensorflow >=1.14.0
        - tensorflow-hub >=0.4.0
      source_files:
        - nlp_primitives/*

  - name: nlp-primitives-complete
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('nlp-primitives', max_pin="x.x.x.x") }}
        - tensorflow >=1.14.0
        - tensorflow-hub >=0.4.0
    test:
      commands:
        - pytest --pyargs nlp_primitives
      imports:
        - nlp_primitives
      requires:
        - pytest >=4.4.1
      source_files:
        - nlp_primitives/*

about:
  doc_url: https://github.com/alteryx/nlp_primitives
  dev_url: https://github.com/alteryx/nlp_primitives
  home: https://github.com/alteryx/nlp_primitives
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library with natural language processing primitives, intended for use with Featuretools.

extra:
  recipe-maintainers:
    - thehomebrewnerd
    - rwedge
    - tamargrey
    - jeff-hernandez
    - dvreed77
    - gsheni
    - chukarsten
    - dsherry
    - eccabay
