{% set version = "2.0.0.dev0" %}

package:
  name: nlp_primitives
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/97/2d/dca84fd129a97d247e60fc57bba4d408abec6fd9cfcba838b4f1cac9929c/nlp_primitives-2.0.0.dev0.tar.gz
  sha256: 7f63f6b28dd82acd79fdc8efface92dc0fd5fc02937bcfb00a5e6036723e91c2

build:
  number: 0

outputs:
  - name: nlp-primitives
    build:
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - pip
        - python >=3.7.*
      run:
        - python >=3.7.*
        - numpy >=1.17.5
        - pandas >=1.3.0
        - featuretools >=1.0.0
        - nltk >=3.4.4
        - scikit-learn >=0.20.0
    test:
      commands:
        - pytest --pyargs nlp_primitives
      imports:
        - nlp_primitives
      requires:
        - pytest >=4.4.1
        - tensorflow >=1.14.0,<2.6.0
        - tensorflow-hub >=0.4.0
      source_files:
        - nlp_primitives/*

  - name: nlp-primitives-complete
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('nlp-primitives', max_pin="x.x.x.x") }}
        - tensorflow >=1.14.0,<2.6.0
        - tensorflow-hub >=0.4.0
    test:
      commands:
        - pytest --pyargs nlp_primitives
      imports:
        - nlp_primitives
      requires:
        - pytest >=4.4.1
      source_files:
        - nlp_primitives/*

about:
  doc_url: https://github.com/FeatureLabs/nlp_primitives
  dev_url: https://github.com/FeatureLabs/nlp_primitives
  home: https://github.com/FeatureLabs/nlp_primitives
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library with natural language processing primitives, intended for use with Featuretools.

extra:
  recipe-maintainers:
    - thehomebrewnerd
    - rwedge
